# Generated by Django 5.1 on 2024-08-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactList',
        ),
    ]
